In [1]:
import pandas as pd

In [2]:
dfs = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')

In [4]:
len(dfs)

2

In [5]:
dfs[0]

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [6]:
dfs[1]

                  Date  Added                                Removed  \
                  Date Ticker                       Security  Ticker
0        June 24, 2024    KKR                            KKR     RHI
1        June 24, 2024   CRWD                    CrowdStrike     CMA
2        June 24, 2024   GDDY                        GoDaddy    ILMN
3          May 8, 2024    VST                         Vistra     PXD
4        April 3, 2024    NaN                            NaN    XRAY
..                 ...    ...                            ...     ...
343       June 9, 1999    WLP                      Wellpoint     HPH
344  December 11, 1998    FSR                        Firstar     LDW
345  December 11, 1998    CCL                 Carnival Corp.     GRN
346  December 11, 1998   CPWR                      Compuware     SUN
347      June 17, 1997    CCI  Countrywide Credit Industries     USL

                                \
                      Security
0                  Robert Half
1                     Comerica
2               Illumina, Inc.
3    Pioneer Natural Resources
4              Dentsply Sirona
..                         ...
343   Harnischfeger Industries
344                      Amoco
345                 General Re
346                 SunAmerica
347                     USLife

                                                Reason
                                                Reason
0                     Market capitalization change.[4]
1                     Market capitalization change.[4]
2                     Market capitalization change.[4]
3    S&P 500 and S&P 100 constituent ExxonMobil acq...
4                     Market capitalization change.[6]
..                                                 ...
343           Harnischfeger filed for bankruptcy.[256]
344                           BP purchased Amoco.[257]
345      Berkshire Hathaway purchased General Re.[257]
346                     AIG purchased SunAmerica.[257]
347                          AIG acquired USLife.[258]

[348 rows x 6 columns]

In [7]:
dfs[0].to_excel('ini_dari_wiki.xlsx', index=False)